VS1-vertical-slice
R2D2-2018/MOTOR_CONTROLLER pull request #8
Opened 2018-05-28 17:21 UTC by BIGduzy

[VS1](https://trello.com/c/95m3Fa1v/16-vs1-vertical-slice) for sprint 3.

2018-05-29 22:02 UTC, vasilishomegas requested changes

2018-05-29 22:02 UTC, vasilishomegas commented on src/motor_interface.hpp
>       * @brief getter for selectedInterface
Check wiki for proper doxygen documentation, you need to document the return value. This goes for the doxygen of other functions as well.

2018-05-29 22:02 UTC, vasilishomegas commented on src/motor_interface.hpp
>  };
Check you indentation, run clang-format.

2018-05-29 22:02 UTC, vasilishomegas commented on src/motor_interface.hpp
>    public:
I see public - private - public.

2018-05-29 22:02 UTC, vasilishomegas commented on src/motor_interface.hpp
> +namespace MotorController {
Indentation of everything within the namespace

2018-05-29 22:05 UTC, vasilishomegas commented
Travis is unhappy, complexity_test and clangformat_test fail.

2018-05-30 09:57 UTC, vasilishomegas commented on src/motor_interface.hpp
> +namespace MotorController {
So apparently this is how it should be...

2018-05-30 09:57 UTC, vasilishomegas commented on src/motor_interface.hpp
>  };
So apparently this is how it should be...

2018-06-03 20:28 UTC, BIGduzy commented
There will be a meeting with the leads about the doxygen for getters and setters on mondag, for now you can ignore them.

2018-06-04 09:10 UTC, BIGduzy commented
No, not yet.

2018-06-04 12:13 UTC, vasilishomegas approved these changes

2018-06-04 14:04 UTC, merged